/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import one.Deadlift;
import one.Exercise;

public class App {

    public static void main(String[] args) {
        // try out your program here
        Exercise exo = new Deadlift(250);
        exo.doExercise();
    }
}
